-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 21:52:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema f1stats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `f1stats` ;

-- -----------------------------------------------------
-- Schema f1stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `f1stats` DEFAULT CHARACTER SET utf8 ;
USE `f1stats` ;

-- -----------------------------------------------------
-- Table `f1stats`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1stats`.`teams` ;

CREATE TABLE IF NOT EXISTS `f1stats`.`teams` (
  `teams_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  PRIMARY KEY (`teams_id`),
  UNIQUE INDEX `teams_id_UNIQUE` (`teams_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1stats`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1stats`.`drivers` ;

CREATE TABLE IF NOT EXISTS `f1stats`.`drivers` (
  `drivers_id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `f_team_id` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `f_races` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  PRIMARY KEY (`drivers_id`),
  UNIQUE INDEX `drivers_id_UNIQUE` (`drivers_id` ASC) VISIBLE,
  INDEX `fk_drivers_teams_idx` (`f_team_id` ASC) VISIBLE,
  CONSTRAINT `fk_drivers_teams`
    FOREIGN KEY (`f_team_id`)
    REFERENCES `f1stats`.`teams` (`teams_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
